// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA08_O7Acgf1R0fUmg0Ji2seIymXH4b6rw',
    appId: '1:1144368098:web:3a2c3d4722fac6c0a4e7bb',
    messagingSenderId: '1144368098',
    projectId: 'chat-app-f7807',
    authDomain: 'chat-app-f7807.firebaseapp.com',
    storageBucket: 'chat-app-f7807.firebasestorage.app',
    measurementId: 'G-90C8D1H9N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASZDnaW5R6x2YI_lpJLPyxFbTebJupsIk',
    appId: '1:1144368098:android:4a0bf5b84cf37b1ea4e7bb',
    messagingSenderId: '1144368098',
    projectId: 'chat-app-f7807',
    storageBucket: 'chat-app-f7807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMm0t_OkNNf4LdEJHISpme2R84Vhsp4Q',
    appId: '1:1144368098:ios:ee249f16a90ab9cea4e7bb',
    messagingSenderId: '1144368098',
    projectId: 'chat-app-f7807',
    storageBucket: 'chat-app-f7807.firebasestorage.app',
    iosClientId:
        '1144368098-6rvtltsaesuubj38tuv8fc2iarq7ke51.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzMm0t_OkNNf4LdEJHISpme2R84Vhsp4Q',
    appId: '1:1144368098:ios:ee249f16a90ab9cea4e7bb',
    messagingSenderId: '1144368098',
    projectId: 'chat-app-f7807',
    storageBucket: 'chat-app-f7807.firebasestorage.app',
    iosClientId:
        '1144368098-6rvtltsaesuubj38tuv8fc2iarq7ke51.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnS1Jv2Rj5CkDimi5VwNsUMvdMpvwLTP8',
    appId: '1:1144368098:web:9f13b77a3509509fa4e7bb',
    messagingSenderId: '1144368098',
    projectId: 'chat-app-f7807',
    authDomain: 'chat-app-f7807.firebaseapp.com',
    storageBucket: 'chat-app-f7807.firebasestorage.app',
    measurementId: 'G-ZXY99GZEWJ',
  );
}
